### ISSUE TITLE
Using this repo

### ISSUE THREAD

**Issue by FavioVazquez** [dpsanders/invitation_to_julia#1]
Hello Dr. Sanders, do you mind if I use this tutorial to teach my colleges some Julia? I'll give you the credit for everything of course.

Thanks.

Favio Vázquez.
ICN - UNAM.

**Comment by Ismael-VC** [comment]
@FavioVazquez I've send you an invitation to join us at [JuliaLangEs](http://www.meetup.com/es/julialanges-mx/) chat room in Spanish!
- https://gitter.im/JuliaLangEs/julialang-es

Please tell your colleges to join too if you think they would be interested.

**Comment by FavioVazquez** [comment]
Great. Thanks!

**Comment by dpsanders** [comment]
Hi Favio:

Of course I don't mind, that's what it's for -- I'm happy to have the material used.
Please send me corrections in the form of Pull Requests.

**Comment by dpsanders** [comment]
You may also be interested in https://github.com/dpsanders/hands_on_julia
which are materials for self study.

There are versions in Spanish at
https://github.com/dpsanders/fisica_computacional

**Comment by FavioVazquez** [comment]
Thanks a lot. Yes I've seem those and your tutorials, they're really good.

Of course, If I find anything I'll send you a PR.

**Comment by dpsanders** [comment]
Thanks! ¡Suerte!
